version: '3.1'

services:
  vlc_player_dc:
    container_name: vlc_player
    #build: .
    image: binacslee/vlc-player:latest
    environment:
      DISPLAY_WIDTH: "1920"
      DISPLAY_HEIGHT: "1080"
    volumes:
      - ./:/work
    ports:
      - 10000:10000